# Generated by Django 3.2.5 on 2021-08-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiControl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light_interval',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='light_interval',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
