# Generated by Django 3.2.5 on 2021-08-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiControl', '0002_auto_20210810_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light_interval',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
