# Generated by Django 3.2.5 on 2021-08-16 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiControl', '0005_humi_sensor_led_screen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temp_humi_calls',
            old_name='humidety',
            new_name='humidity',
        ),
        migrations.AddField(
            model_name='temp_humi_calls',
            name='read_rime',
            field=models.TimeField(default=datetime.datetime(2021, 8, 16, 20, 19, 19, 548348)),
        ),
    ]
