# Generated by Django 3.2.5 on 2021-09-05 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiControl', '0006_auto_20210816_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_humi_calls',
            name='read_rime',
            field=models.TimeField(default=datetime.datetime(2021, 9, 6, 0, 31, 13, 582728)),
        ),
    ]
